version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "your-mongo-db-uri"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
